version: "3.9"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
      # If you use Vite, uncomment this:
      # args:
      #   BUILD_DIR: dist
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - .env